# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='phone',
            field=models.BigIntegerField(blank=True, unique=True),
        ),
    ]
