# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tobe', '0003_auto_20171003_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='todolist',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_assigned_to', to='tobe.TodoUser'),
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='created_by',
        ),
        migrations.AddField(
            model_name='todolist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_created_by', to='tobe.TodoUser'),
        ),
    ]
