# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobe', '0004_auto_20171003_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoAuthtoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=56)),
            ],
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='completed',
            new_name='isdeleted',
        ),
        migrations.AddField(
            model_name='todolist',
            name='isaccepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todolist',
            name='iscompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todouser',
            name='auth_token',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='todouser',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
