# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tobe', '0005_auto_20171003_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoAuthtoken',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
